name: Test python 3.9 compat

on:
  push:
    branches:
      - '*'  # Any branch
  pull_request:
    branches:
      - '*'  # Any branch
      
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        
    - name: Update pip
      run: python -m pip install --upgrade pip
      
    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: '2022'  # Specify your Visual Studio version
        
    - name: Build test host
      run: cl /EHsc /Fe:test_host.exe test_python_39/test.cpp
      
    - name: Run RUN.BAT
      run: test_python_39/test_host.exe
