name: Test python 3.9 compat

on:
  push:
    branches:
      - '*'  # Any branch
  pull_request:
    branches:
      - '*'  # Any branch
      
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        
    - name: Update pip
      run: python -m pip install --upgrade pip
      
    - name: Install Clang
      run: choco install llvm
        
    - name: Build test host
      run: clang++ -o test_host test_python_39/test.cpp
      
    - name: Run RUN.BAT
      run: ./test_host.exe
